project:
  type: website

website:
  title: "ANLY 503: Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  sidebar: false
  search: false

format:
  html:
    theme: 
     - cosmo
     - custom.scss
    page-layout: full
    css: styles.css
    toc: true
    embed-resources: true
    mainfont: Optima

editor: visual

